# Random Function

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.28610465])

In [3]:
np.random.random(4)

array([0.91663744, 0.26668557, 0.08707624, 0.35261966])

In [4]:
np.random.random((4,4))

array([[0.76852844, 0.53929054, 0.61990231, 0.98073915],
       [0.11569162, 0.87246341, 0.23306568, 0.96326108],
       [0.14812968, 0.71032748, 0.53122094, 0.43966541],
       [0.00561217, 0.05654376, 0.79480675, 0.49670612]])

In [5]:
np.random.randint(1)

0

In [6]:
np.random.randint(1,7)

4

In [7]:
np.random.randint(1,7,(4,4))

array([[6, 4, 4, 3],
       [6, 2, 2, 3],
       [6, 6, 5, 6],
       [5, 2, 2, 3]])

In [8]:
np.random.rand(3)

array([0.55665666, 0.3113757 , 0.73790063])

In [9]:
np.random.rand(5,6)

array([[0.87646333, 0.39467251, 0.02680061, 0.89616973, 0.36052095,
        0.8465465 ],
       [0.9419497 , 0.38048521, 0.5020054 , 0.71533711, 0.18688003,
        0.17390338],
       [0.42868902, 0.08528693, 0.87584526, 0.62000905, 0.88291112,
        0.04947276],
       [0.19209829, 0.05586677, 0.20725203, 0.23240472, 0.43608304,
        0.2429463 ],
       [0.83637085, 0.35490639, 0.77739936, 0.06749186, 0.43737334,
        0.40397503]])

In [10]:
np.random.randn(6)

array([-1.82626229, -0.87298835,  0.01318505,  0.26254118,  0.99219124,
        0.1601104 ])

In [11]:
np.random.seed(15)
np.random.randint(1,7,(4,4,4))

array([[[1, 6, 5, 6],
        [1, 5, 4, 4],
        [6, 6, 2, 6],
        [1, 3, 5, 2]],

       [[6, 4, 5, 6],
        [5, 6, 1, 3],
        [2, 2, 1, 6],
        [3, 3, 4, 3]],

       [[2, 1, 6, 2],
        [3, 1, 1, 1],
        [5, 4, 5, 3],
        [3, 1, 6, 4]],

       [[1, 6, 5, 6],
        [4, 2, 1, 1],
        [6, 6, 5, 1],
        [5, 2, 3, 1]]])

In [12]:
np.random.seed(15)
np.random.randint(1,7,(4,4,4))

array([[[1, 6, 5, 6],
        [1, 5, 4, 4],
        [6, 6, 2, 6],
        [1, 3, 5, 2]],

       [[6, 4, 5, 6],
        [5, 6, 1, 3],
        [2, 2, 1, 6],
        [3, 3, 4, 3]],

       [[2, 1, 6, 2],
        [3, 1, 1, 1],
        [5, 4, 5, 3],
        [3, 1, 6, 4]],

       [[1, 6, 5, 6],
        [4, 2, 1, 1],
        [6, 6, 5, 1],
        [5, 2, 3, 1]]])

In [13]:
N=[1,2,3,4,5]
np.random.choice(N)

5

In [14]:
N=[1,2,3,4,5]
np.random.choice(N)

4

In [15]:

np.random.permutation(N)

array([1, 4, 5, 2, 3])

In [16]:
for i in range(20):
    print(np.random.choice(N))

3
3
3
3
1
3
1
5
5
5
4
5
1
2
1
5
1
4
3
5
