# NUMPY FUNCTIONS

In [1]:
import numpy as np

# ARANGE FUNCTION

In [2]:
range_1=np.arange(1,13)
print(range_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
range_2=np.arange(1,13,3)
print(range_2)

[ 1  4  7 10]


# LINSPACE FUNCTION

In [4]:
range_3=np.linspace(1,13,20)
print(range_3)

[ 1.          1.63157895  2.26315789  2.89473684  3.52631579  4.15789474
  4.78947368  5.42105263  6.05263158  6.68421053  7.31578947  7.94736842
  8.57894737  9.21052632  9.84210526 10.47368421 11.10526316 11.73684211
 12.36842105 13.        ]


# RESHAPE FUNCTION

In [5]:
range_9=range_1.reshape(2,6)
print(range_9)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
range_4=range_1.reshape(2,3,2)
print(range_4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
range_5=np.arange(1,13).reshape(4,3)
print(range_5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# TRANSPOSE FUNCTION

In [8]:
range_5.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [9]:
range_2.T

array([ 1,  4,  7, 10])

# FLAATTEN FUNCTION

In [10]:
range_4.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# RAVEL FUNCTION

In [11]:
range_4.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])