In [1]:
import numpy as np

In [2]:
matrix_1=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
mx=np.ones(7)

In [4]:
print(mx)

[1. 1. 1. 1. 1. 1. 1.]


In [7]:
mx=np.ones(7,dtype=int)
print(mx)

[1 1 1 1 1 1 1]


In [8]:
mx=np.ones((2,3))
print(mx)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
mx=np.zeros(7,dtype=int)
print(mx)

[0 0 0 0 0 0 0]


In [10]:
mx=np.zeros((4,4),dtype=bool)
print(mx)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [11]:
mx=np.zeros((4,4),dtype=str)
print(mx)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [12]:
empty=''
print(bool(''))

False


In [14]:
mx=np.empty((4,4))      #empty matrix
print(mx)  

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 6.23058707e-307]
 [2.22522597e-306 1.33511969e-306 1.37962320e-306 9.34604358e-307]
 [9.79101082e-307 1.78020576e-306 1.69119873e-306 2.22522868e-306]
 [1.24611809e-306 8.06632139e-308 1.60221208e-306 2.29178686e-312]]
