# Python Concatenation and split

In [1]:
import numpy as np

In [2]:
mx1=np.arange(1,17).reshape(4,4)
print(mx1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
mx2=np.arange(17,33).reshape(4,4)
print(mx2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [4]:
list1=[1,2,3,4]
list2=[5,6,7,8]

In [5]:
list1+list2

[1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
mx1+mx2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [7]:
np.concatenate((mx1,mx2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [8]:
np.vstack((mx1,mx2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [9]:
np.concatenate((mx1,mx2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [10]:
np.concatenate((mx1,mx2,mx1),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [11]:
np.hstack((mx1,mx2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [12]:
np.split(mx1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [13]:
list1=np.split(mx1,2)

In [14]:
type(list1)

list

In [15]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
type(list1[0])

numpy.ndarray

In [18]:
d1=np.array([1,2,3,4,7,8])
print(d1)

[1 2 3 4 7 8]


In [19]:
np.split(d1,[1,4])

[array([1]), array([2, 3, 4]), array([7, 8])]

In [20]:
np.split(mx2,2,axis=1)

[array([[17, 18],
        [21, 22],
        [25, 26],
        [29, 30]]), array([[19, 20],
        [23, 24],
        [27, 28],
        [31, 32]])]