In [1]:
import numpy as np

In [2]:
array_1=np.array([1,2,3,4])
print(array_1)

[1 2 3 4]


In [3]:
type(array_1)

numpy.ndarray

In [4]:
array_1.ndim

1

In [5]:
array_1.size

4

In [6]:
array_1.dtype

dtype('int32')

In [7]:
array_2=np.array([[1,2,3,4],[5,6,7,8]])
print(array_2)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
type(array_2)

numpy.ndarray

In [9]:
array_2.ndim

2

In [10]:
array_2.size

8